CREATE TABLE users (
id INT  AUTO_INCREMENT NOT NULL ,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
age INT NOT NULL,
address VARCHAR(50),
joining_date DATE NOT NULL,
PRIMARY KEY(id)
);

